### ISSUE TITLE
doesn't work when hosted on a linux box

### ISSUE THREAD

**Issue by deostroll** [einfallstoll/express-ntlm#11]
I get ```req.ntlm``` as ```undefined``` when I run this code from a linux box.

```javascript
var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  var user = JSON.stringify(req.ntlm);
  console.log('req.ntlm:', req.ntlm);
  res.render('index', { title: 'Express', user: user });
});

module.exports = router;
```

**Comment by einfallstoll** [comment]
Where did you include the `express-ntlm` middleware?

**Comment by deostroll** [comment]
In `app.js`:

```javascript
var ntlm = require('express-ntlm');
//...
//...
app.use(ntlm({
        domain:'MyDomain',
        domaincontroller:'ldap://my.domain.controller.com',
        debug: function() {
                var args = [].slice.call(arguments);
                console.log.apply(null, args);
        }
}));
```

**Comment by einfallstoll** [comment]
From [express.js](http://expressjs.com/api.html#router):
> A router object is an isolated instance of middleware and routes. You can think of it as a “mini-application,” capable only of performing middleware and routing functions.

It's required to include the middleware for your router as well:

```
var express = require('express');
var ntlm = require('express-ntlm');
var router = express.Router();

router.use(ntlm({
        domain:'MyDomain',
        domaincontroller:'ldap://my.domain.controller.com',
        debug: function() {
                var args = [].slice.call(arguments);
                console.log.apply(null, args);
        }
}));

/* GET home page. */
router.get('/', function(req, res, next) {
  var user = JSON.stringify(req.ntlm);
  console.log('req.ntlm:', req.ntlm);
  res.render('index', { title: 'Express', user: user });
});

module.exports = router;
```

**Comment by deostroll** [comment]
Now it gives the following error:

```
$ npm start

> surveyexpress@0.0.0 start /home/admin/Public/web/surveyexpress
> node ./bin/www

/home/admin/Public/web/surveyexpress/node_modules/express/node_modules/finalhandler/index.js:58
    var status = res.statusCode
                    ^
TypeError: Cannot read property 'statusCode' of undefined
    at /home/admin/Public/web/surveyexpress/node_modules/express/node_modules/finalhandler/index.js:58:21
    at EventEmitter.handle (/home/admin/Public/web/surveyexpress/node_modules/express/lib/application.js:169:5)
    at app (/home/admin/Public/web/surveyexpress/node_modules/express/lib/express.js:38:9)
    at Object.<anonymous> (/home/admin/Public/web/surveyexpress/routes/index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! surveyexpress@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the surveyexpress@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the surveyexpress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls surveyexpress
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/Public/web/surveyexpress/npm-debug.log
```

The `npm-debug.log`:

```
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart surveyexpress@0.0.0
6 info start surveyexpress@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info surveyexpress@0.0.0 Failed to exec start script
9 verbose stack Error: surveyexpress@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid surveyexpress@0.0.0
11 verbose cwd /home/admin/Public/web/surveyexpress
12 error Linux 3.10.0-123.el7.x86_64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error surveyexpress@0.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the surveyexpress@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the surveyexpress package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls surveyexpress
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by einfallstoll** [comment]
This error does not look like one from `express-ntlm`. Within the module it just appends a property to `request` and `response` and the other properties are not touched at all.

**Comment by deostroll** [comment]
I agree. But it happens specifically in that `router.use` call. Can you give me some pointers to debug this...

**Comment by deostroll** [comment]
Okay, I tried this in the app middleware it works...

I've tried the same bit of code given as example: https://github.com/einfallstoll/express-ntlm#example-usage

**Comment by einfallstoll** [comment]
Maybe this error occurs because `express-ntlm` closes several responses by itself during the authentication.

I'll close this as it seems to be resolved. If there are any problems or other questions feel free to reopen this issue or create a new one.
