### ISSUE TITLE
Session.id vs connection.id

### ISSUE THREAD

**Issue by microspace** [einfallstoll/express-ntlm#69]
I'm trying to use express-ntlm for authentication and express-session for authorisation of user.
I get new request.connection.id every time I refresh the page. But session.id persists until I quit browser or session expires. So for I single session.id I get multiple connection.id.

Is there a way to check if cookie is set for the page before trying ntlm auth? 
Or maybe I should not bother and refresh session.id with every page refresh?

**Comment by einfallstoll** [comment]
NTLM is designed to authenticate connections only. I'd suggest to create some conditional middleware:

```
const express = require('express');
const session = require('express-session');
const ntlm = require('express-ntlm')({
  domain: 'MYDOMAIN',
  domaincontroller: 'ldap://myad.example',
});

// read / initialise user session
app.use(session());

// custom middleware
app.use((req, res, next) => {
  const userIsAuthenticated = /* req.session.user */;
  if (userIsAuthenticated) {
    // if the user has a valid session, they are already authenticated, so we can go to the next route
    next();
  } else {
    // otherwise, we need to call the NTLM authentication
    // it's important to call it directly
    ntlm(req, res, () => {
      // express-ntlm will call next (this function here) after successful authentication, so we can e.g. read the user from the database or save the username to the session and then call the next route
      /* req.session.user = req.ntlm.UserName; */
      next();
    });
  }
});
```

I just wrote this from top of my head, maybe this doesn't work at all, but you get the idea. 😁

**Comment by microspace** [comment]
@einfallstoll , thank you for responce!
I get `TypeError: Cannot read property 'id' of undefined` error at `ntlm(req, res, () => {`. 

Is it `connection.id`? I'm Could it be because I use typescript?

**Comment by einfallstoll** [comment]
@microspace Can't tell without stack trace

**Comment by microspace** [comment]
If I remove `app.use(session());` from your code, problem disappears. I seems to me that session middleware messes something with request. 
```

TypeError: Cannot read property 'id' of undefined
at FrontendApplication.ntlm (/myproject/packages/frontend/node_modules/express-ntlm/lib/express-ntlm.js:199:33)

at /myproject/packages/frontend/src/frontend_application.ts:166:16

at Layer.handle [as handle_request] (/myproject/packages/frontend/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/myproject/packages/frontend/node_modules/express/lib/router/index.js:317:13)

at /myproject/packages/frontend/node_modules/express/lib/router/index.js:284:7

at Function.process_params (/myproject/packages/frontend/node_modules/express/lib/router/index.js:335:12)

at next (/myproject/packages/frontend/node_modules/express/lib/router/index.js:275:10)

at /myproject/packages/frontend/node_modules/express-session/index.js:502:7

at Command.callback (/myproject/packages/frontend/node_modules/connect-redis/lib/connect-redis.js:42:16)

at normal_reply (/myproject/packages/frontend/node_modules/redis/index.js:654:21)

at RedisClient.return_reply (/myproject/packages/frontend/node_modules/redis/index.js:752:9)

at JavascriptRedisParser.returnReply (/myproject/packages/frontend/node_modules/redis/index.js:137:18)

at JavascriptRedisParser.execute (/myproject/packages/frontend/node_modules/redis-parser/lib/parser.js:544:14)

at Socket.<anonymous> (/myproject/packages/frontend/node_modules/redis/index.js:218:27)

at Socket.emit (events.js:223:5)

at Socket.EventEmitter.emit (domain.js:475:20)
```

**Comment by microspace** [comment]
I've tried your example with plain js and it work great! So issue is with typescript.

Thank you for your help!
